### ISSUE TITLE
Flesh out README

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-optional-features#1]
https://drive.google.com/file/d/1xPf56h_ANASOQo4Ay8hsn_JBnRemgVa3/view?usp=sharing

**Comment by rwwagner90** [comment]
I can do this 👍

**Comment by chancancode** [comment]
Please do! You can refer to the video or ask questions here/on slack (#dev-ember) if you need help.

**Comment by rwwagner90** [comment]
@chancancode I did a first pass. Please let me know if it needs adjustments!
