### ISSUE TITLE
Feature option is not being reflected when app renders

### ISSUE THREAD

**Issue by dorilla** [emberjs/ember-optional-features#11]
## Summary
After disabling `application-template-wrapper`, the top-level wrapper div is still rendered and the application is still nested under it.

## Steps to setup:
1. Brand new ember application
2. `ember install @ember/optional-features`
3. `ember feature:disable application-template-wrapper`

#### My `config/optional-features.json`
```
{
  "application-template-wrapper": false
}
```

#### My `application.hbs`
```
<div class="ember-view">
  {{!-- The following component displays Ember's default welcome message. --}}
  {{welcome-page}}
  {{!-- Feel free to remove this! --}}

  {{outlet}}
</div>
```

#### Rendered in the browser:
![image](https://user-images.githubusercontent.com/1843695/36731823-e3268a4a-1b99-11e8-904d-306dd61ac811.png)

#### Ember -v
```
ember-cli: 3.1.0-beta.1
node: 8.7.0
os: darwin x64
```

#### debugging console:
```
DEBUG: -------------------------------
DEBUG: Ember      : 3.1.0-beta.2
DEBUG: Ember Data : 3.1.0-beta.1
DEBUG: jQuery     : 3.3.1
DEBUG: -------------------------------
```

Here is a link to the ember app I set up for this: https://github.com/dorilla/ember-test-no-wrap

Thanks for your help! And I'm assuming i did something wrong somewhere in my setup, any help is appreciated.

**Comment by alkamin** [comment]
I am experiencing this problem also.

Version of this addon:
`"@ember/optional-features": "^0.5.1"`

Ember -v
```
ember-cli: 3.1.0-beta.1
node: 6.9.2
os: darwin x64
```

```
DEBUG: -------------------------------
DEBUG: Ember  : 3.1.0-beta.2
DEBUG: jQuery : 3.3.1
DEBUG: -------------------------------
```

I also created a minimal app that also had the same problem: https://github.com/alkamin/ember-application-template-wrapper-test

**Comment by tchak** [comment]
Same problem here with ˋember-3.1-beta3ˋ

**Comment by chancancode** [comment]
I can reproduce this. Seems like the problem is [this line](https://github.com/emberjs/ember-optional-features/blob/master/index.js#L23) doesn't do what I think. It calls [`project.require`](https://github.com/ember-cli/ember-cli/blob/master/lib/models/project.js#L346) which then calls [`resolve.sync`](https://github.com/ember-cli/ember-cli/blob/master/lib/models/project.js#L330) like this:

```
> resolve.sync('config/optional-features.json', { basedir: '/private/tmp/ember-test-no-wrap' })
Error: Cannot find module 'config/optional-features.json' from '/private/tmp/ember-test-no-wrap'
```

I suppose we could just call `require` manually (using `this.project.root`), or perhaps there is another Ember CLI API we are supposed to use here?

cc @rwjblue

**Comment by chancancode** [comment]
Aha. Seems like this works:

```
> resolve.sync('./config/optional-features.json', { basedir: '/private/tmp/ember-test-no-wrap' })
'/private/tmp/ember-test-no-wrap/config/optional-features.json'
```

So, we probably just need to add the missing `./` to [this line](https://github.com/emberjs/ember-optional-features/blob/master/index.js#L23).

**Comment by chancancode** [comment]
@dorilla @alkamin @tchak can you confirm the latest release fixes the issue?

**Comment by chancancode** [comment]
I tried with `ember-test-no-wrap` locally and it seems to have worked!

**Comment by alkamin** [comment]
Upgraded my test app and it works.

**Comment by dorilla** [comment]
I can confirm the fix worked! Thanks for the speedy work guys! Very much appreciated.
