### ISSUE TITLE
feature:enable, feature:disable commands update the optional-fatures.js file thus replacing existing key:value with new ones.  May want to append to the file, rather than replace/update.  

### ISSUE THREAD

**Issue by AvinishSharma** [emberjs/ember-optional-features#134]
Each time this one of feature:enable, feature:disable commands is executed, optional-features.js file is updated (existing key: value in the file are replaced with the new one) not appended.  This caused a bit of a heartache for me as it put me in a loop for a bit. :slightly_smiling_face:  I had to manually edit the file and the key:values to the object inside it.

**Comment by rwjblue** [comment]
Thanks for reporting! I'm going to look into this later today...

**Comment by simonihmig** [comment]
@AvinishSharma Is this in an addon, or using a custom config path? If so, sounds like a duplicate of #74!?

**Comment by rwjblue** [comment]
I think this is resolved now (thanks @simonihmig!).
