### ISSUE TITLE
Tests fail with latest version of ember-cli-version-checker

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember-optional-features#16]
Apparently https://github.com/emberjs/ember-optional-features/blob/0bc704f012b0796834406883168b0abe825715df/commands/index.js#L27 should be `this.project`

However `this` is a command, and it does not have a `project` property, event when it should.

**Comment by rwjblue** [comment]
This was fixed in https://github.com/emberjs/ember-optional-features/pull/15
