### ISSUE TITLE
Support reading options from process.env

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-optional-features#2]
The presence of `process.env.EMBER_OPTIONAL_FEATURES` should override `config/optional-features.{js,json}`.

This mechanism will be how ember-try scenarios can test different configurations...

**Comment by chancancode** [comment]
If we have that do we still need to support .js?

**Comment by rwjblue** [comment]
I would think not?

**Comment by chancancode** [comment]
:+1: makes my life easier

**Comment by chancancode** [comment]
This is pretty easy for me to do, but I have some questions

1. if you have `process.env.EMBER_OPTIONAL_FEATURES`, it should completely override the json file right?
2. presumably, the list is comma separated
3. if you _didn't_ include something, does it mean "use the default" or "disable"? (whatever we pick, how would you say the _other_ thing)?

**Comment by chancancode** [comment]
or would the value of `EMBER_OPTIONAL_FEATURES` just be the JSON string?

**Comment by rwjblue** [comment]
> if you have process.env.EMBER_OPTIONAL_FEATURES, it should completely override the json file right?

Yes

> the value of EMBER_OPTIONAL_FEATURES just be the JSON string?

Right, this was what I was thinking...

**Comment by kategengler** [comment]
I had thought it would merge with the json file, with the environment variable having precedence. So if I care about testing jQueryDisabled on & off, in ember-try, I can specify just that flag and not worry about the values of the other.
